<?php
/*
 * Simple Demo of Duo's Web SDK
 *
 * Simple login form with hardcoded username/password
 * protected using Duo
 *
 * User: demo
 * Password: letmein
 */

include('duo_web.php');

/*
 * This is something uniquely generated by you for your application
 * and is not shared with Duo.
 */
define('AKEY',"THISISMYSUPERSECRETCUSTOMERKEYDONOTSHARE");

/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
 * on the integrations page.
 */
define('IKEY',"");
define('SKEY',"");
define('HOST',"");
/* 
 * For security reasons, the above keys are best stored outside of
 * the webroot in a production implementation.
 */


echo "<h1>Duo Security Web SDK Demo</h1>";
echo "Username: demo <br>Password: letmein <br><br><br><hr>";


/*
 * STEP 3:
 * Once secondary auth has completed you may log in the user
 */
if(isset($_POST['sig_response'])){ //verify sig response and log in user
	//make sure that verifyResponse does not return NULL
	//if it is NOT NULL then it will return a username
	//you can then set any cookies/session data for that username
	//and complete the login process
	$resp = Duo::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);
	if($resp != NULL){
		//password protected content would go here
		echo 'hi, ' . $resp . '<br>';
		echo 'Your content here!';
	}
}


/*
 * STEP 2:
 * verify username and password
 * if the user and pass are good, then generate a sig_request and
 * load up the Duo iframe for secondary authentication
 */
else if(isset($_POST['user']) && isset($_POST['pass'])){
	if($_POST['user'] == 'demo' && $_POST['pass'] == 'letmein') { //run secondary auth
		//generate sig request and then load up Duo javascript and iframe
		$sig_request = Duo::signRequest(IKEY, SKEY, AKEY, $_POST['user']);
?>
		<script src="Duo-Web-v1.bundled.min.js"></script>
		<input type="hidden" id="duo_host" value="<?php echo HOST ; ?>">
		<input type="hidden" id="duo_sig_request" value="<?php echo $sig_request; ?>">
		<script src="Duo-Init.js"></script>

		<iframe id="duo_iframe" width="620" height="500" frameborder="0" allowtransparency="true" style="background: transparent;"></iframe>
<?php
	}
}

/* STEP 1: login form
 * handled exactly as usual
 */
else {
	//output simple login form
	echo "<form action='index.php' method='post'>";
	echo "Username: <input type='text' name='user' /> <br />";
	echo "Password: <input type='password' name='pass' /> <br />";
	echo "<input type='submit' value='Submit' />";
	echo "</form>";
}

?>
